// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcjwzdxejaoivwvvnbcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxjand6ZHhlamFvaXZ3dnZuYmNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MDM0NjQsImV4cCI6MjA2MTA3OTQ2NH0.5DEgrWg_DWXZj-ZhkDzw5F5IHVafp_3kI_eb7o9OJSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);